// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/patronireceiver component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("patronireceiver")
	ScopeName = "patronireceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
	TracesStability  = component.StabilityLevelDevelopment
	LogsStability    = component.StabilityLevelDevelopment
)
