// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
	testDataSetReag
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "reaggregate_set",
			metricsSet:  testDataSetReag,
			resAttrsSet: testDataSetReag,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))
			aggMap := make(map[string]string) // contains the aggregation strategies for each metric name
			aggMap["patroni.cluster.unlocked"] = mb.metricPatroniClusterUnlocked.config.AggregationStrategy
			aggMap["patroni.dcs_last_seen"] = mb.metricPatroniDcsLastSeen.config.AggregationStrategy
			aggMap["patroni.failsafe_mode.active"] = mb.metricPatroniFailsafeModeActive.config.AggregationStrategy
			aggMap["patroni.history.lsn"] = mb.metricPatroniHistoryLsn.config.AggregationStrategy
			aggMap["patroni.history.promoted_at"] = mb.metricPatroniHistoryPromotedAt.config.AggregationStrategy
			aggMap["patroni.history.size"] = mb.metricPatroniHistorySize.config.AggregationStrategy
			aggMap["patroni.is_paused"] = mb.metricPatroniIsPaused.config.AggregationStrategy
			aggMap["patroni.pending_restart"] = mb.metricPatroniPendingRestart.config.AggregationStrategy
			aggMap["patroni.postgres.in_archive_recovery"] = mb.metricPatroniPostgresInArchiveRecovery.config.AggregationStrategy
			aggMap["patroni.postgres.running"] = mb.metricPatroniPostgresRunning.config.AggregationStrategy
			aggMap["patroni.postgres.server_version"] = mb.metricPatroniPostgresServerVersion.config.AggregationStrategy
			aggMap["patroni.postgres.state"] = mb.metricPatroniPostgresState.config.AggregationStrategy
			aggMap["patroni.postgres.streaming"] = mb.metricPatroniPostgresStreaming.config.AggregationStrategy
			aggMap["patroni.postgres.timeline"] = mb.metricPatroniPostgresTimeline.config.AggregationStrategy
			aggMap["patroni.postmaster_start_time"] = mb.metricPatroniPostmasterStartTime.config.AggregationStrategy
			aggMap["patroni.primary"] = mb.metricPatroniPrimary.config.AggregationStrategy
			aggMap["patroni.quorum_standby"] = mb.metricPatroniQuorumStandby.config.AggregationStrategy
			aggMap["patroni.replica"] = mb.metricPatroniReplica.config.AggregationStrategy
			aggMap["patroni.replication.lag"] = mb.metricPatroniReplicationLag.config.AggregationStrategy
			aggMap["patroni.replication.receive_lag"] = mb.metricPatroniReplicationReceiveLag.config.AggregationStrategy
			aggMap["patroni.replication.replay_lag"] = mb.metricPatroniReplicationReplayLag.config.AggregationStrategy
			aggMap["patroni.standby_leader"] = mb.metricPatroniStandbyLeader.config.AggregationStrategy
			aggMap["patroni.sync_standby"] = mb.metricPatroniSyncStandby.config.AggregationStrategy
			aggMap["patroni.version"] = mb.metricPatroniVersion.config.AggregationStrategy
			aggMap["patroni.xlog.location"] = mb.metricPatroniXlogLocation.config.AggregationStrategy
			aggMap["patroni.xlog.paused"] = mb.metricPatroniXlogPaused.config.AggregationStrategy
			aggMap["patroni.xlog.received_location"] = mb.metricPatroniXlogReceivedLocation.config.AggregationStrategy
			aggMap["patroni.xlog.replayed_location"] = mb.metricPatroniXlogReplayedLocation.config.AggregationStrategy
			aggMap["patroni.xlog.replayed_timestamp"] = mb.metricPatroniXlogReplayedTimestamp.config.AggregationStrategy

			expectedWarnings := 0
			if tt.metricsSet != testDataSetReag {
				assert.Equal(t, expectedWarnings, observedLogs.Len())
			}

			defaultMetricsCount := 0
			allMetricsCount := 0
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniClusterUnlockedDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniClusterUnlockedDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniDcsLastSeenDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniDcsLastSeenDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniFailsafeModeActiveDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniFailsafeModeActiveDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniHistoryLsnDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val", 24, "patroni.history.reason-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniHistoryLsnDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2", 25, "patroni.history.reason-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniHistoryPromotedAtDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val", 24, "patroni.history.reason-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniHistoryPromotedAtDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2", 25, "patroni.history.reason-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniHistorySizeDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniHistorySizeDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniIsPausedDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniIsPausedDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniPendingRestartDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniPendingRestartDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniPostgresInArchiveRecoveryDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniPostgresInArchiveRecoveryDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniPostgresRunningDataPoint(ts, 1, "patroni.node.name-val", "patroni.role-val", "patroni.scope-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniPostgresRunningDataPoint(ts, 3, "patroni.node.name-val-2", "patroni.role-val-2", "patroni.scope-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniPostgresServerVersionDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniPostgresServerVersionDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniPostgresStateDataPoint(ts, 1, "patroni.node.name-val", "patroni.role-val", "patroni.scope-val", "patroni.state-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniPostgresStateDataPoint(ts, 3, "patroni.node.name-val-2", "patroni.role-val-2", "patroni.scope-val-2", "patroni.state-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniPostgresStreamingDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniPostgresStreamingDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniPostgresTimelineDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniPostgresTimelineDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniPostmasterStartTimeDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniPostmasterStartTimeDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniPrimaryDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniPrimaryDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniQuorumStandbyDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniQuorumStandbyDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniReplicaDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniReplicaDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniReplicationLagDataPoint(ts, 1, "patroni.node.name-val", "patroni.replication.application_name-val", "patroni.replication.client_addr-val", "patroni.replication.sync_state-val", "patroni.scope-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniReplicationLagDataPoint(ts, 3, "patroni.node.name-val-2", "patroni.replication.application_name-val-2", "patroni.replication.client_addr-val-2", "patroni.replication.sync_state-val-2", "patroni.scope-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniReplicationReceiveLagDataPoint(ts, 1, "patroni.node.name-val", "patroni.replication.application_name-val", "patroni.replication.client_addr-val", "patroni.replication.sync_state-val", "patroni.scope-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniReplicationReceiveLagDataPoint(ts, 3, "patroni.node.name-val-2", "patroni.replication.application_name-val-2", "patroni.replication.client_addr-val-2", "patroni.replication.sync_state-val-2", "patroni.scope-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniReplicationReplayLagDataPoint(ts, 1, "patroni.node.name-val", "patroni.replication.application_name-val", "patroni.replication.client_addr-val", "patroni.replication.sync_state-val", "patroni.scope-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniReplicationReplayLagDataPoint(ts, 3, "patroni.node.name-val-2", "patroni.replication.application_name-val-2", "patroni.replication.client_addr-val-2", "patroni.replication.sync_state-val-2", "patroni.scope-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniStandbyLeaderDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniStandbyLeaderDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniSyncStandbyDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniSyncStandbyDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniVersionDataPoint(ts, 1, "patroni.node.name-val", "patroni.scope-val", "patroni.version-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniVersionDataPoint(ts, 3, "patroni.node.name-val-2", "patroni.scope-val-2", "patroni.version-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniXlogLocationDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniXlogLocationDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniXlogPausedDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniXlogPausedDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniXlogReceivedLocationDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniXlogReceivedLocationDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniXlogReplayedLocationDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniXlogReplayedLocationDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordPatroniXlogReplayedTimestampDataPoint(ts, 1, "patroni.scope-val", "patroni.node.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordPatroniXlogReplayedTimestampDataPoint(ts, 3, "patroni.scope-val-2", "patroni.node.name-val-2")
			}

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))
			if tt.name == "reaggregate_set" {
				assert.Empty(t, mb.metricPatroniClusterUnlocked.aggDataPoints)
				assert.Empty(t, mb.metricPatroniDcsLastSeen.aggDataPoints)
				assert.Empty(t, mb.metricPatroniFailsafeModeActive.aggDataPoints)
				assert.Empty(t, mb.metricPatroniHistoryLsn.aggDataPoints)
				assert.Empty(t, mb.metricPatroniHistoryPromotedAt.aggDataPoints)
				assert.Empty(t, mb.metricPatroniHistorySize.aggDataPoints)
				assert.Empty(t, mb.metricPatroniIsPaused.aggDataPoints)
				assert.Empty(t, mb.metricPatroniPendingRestart.aggDataPoints)
				assert.Empty(t, mb.metricPatroniPostgresInArchiveRecovery.aggDataPoints)
				assert.Empty(t, mb.metricPatroniPostgresRunning.aggDataPoints)
				assert.Empty(t, mb.metricPatroniPostgresServerVersion.aggDataPoints)
				assert.Empty(t, mb.metricPatroniPostgresState.aggDataPoints)
				assert.Empty(t, mb.metricPatroniPostgresStreaming.aggDataPoints)
				assert.Empty(t, mb.metricPatroniPostgresTimeline.aggDataPoints)
				assert.Empty(t, mb.metricPatroniPostmasterStartTime.aggDataPoints)
				assert.Empty(t, mb.metricPatroniPrimary.aggDataPoints)
				assert.Empty(t, mb.metricPatroniQuorumStandby.aggDataPoints)
				assert.Empty(t, mb.metricPatroniReplica.aggDataPoints)
				assert.Empty(t, mb.metricPatroniReplicationLag.aggDataPoints)
				assert.Empty(t, mb.metricPatroniReplicationReceiveLag.aggDataPoints)
				assert.Empty(t, mb.metricPatroniReplicationReplayLag.aggDataPoints)
				assert.Empty(t, mb.metricPatroniStandbyLeader.aggDataPoints)
				assert.Empty(t, mb.metricPatroniSyncStandby.aggDataPoints)
				assert.Empty(t, mb.metricPatroniVersion.aggDataPoints)
				assert.Empty(t, mb.metricPatroniXlogLocation.aggDataPoints)
				assert.Empty(t, mb.metricPatroniXlogPaused.aggDataPoints)
				assert.Empty(t, mb.metricPatroniXlogReceivedLocation.aggDataPoints)
				assert.Empty(t, mb.metricPatroniXlogReplayedLocation.aggDataPoints)
				assert.Empty(t, mb.metricPatroniXlogReplayedTimestamp.aggDataPoints)
			}

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "patroni.cluster.unlocked":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.cluster.unlocked"], "Found a duplicate in the metrics slice: patroni.cluster.unlocked")
						validatedMetrics["patroni.cluster.unlocked"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if the cluster is unlocked (no leader lock held), 0 if locked.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.cluster.unlocked"], "Found a duplicate in the metrics slice: patroni.cluster.unlocked")
						validatedMetrics["patroni.cluster.unlocked"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if the cluster is unlocked (no leader lock held), 0 if locked.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.cluster.unlocked"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.dcs_last_seen":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.dcs_last_seen"], "Found a duplicate in the metrics slice: patroni.dcs_last_seen")
						validatedMetrics["patroni.dcs_last_seen"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Epoch timestamp when DCS was last contacted successfully by Patroni.", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.dcs_last_seen"], "Found a duplicate in the metrics slice: patroni.dcs_last_seen")
						validatedMetrics["patroni.dcs_last_seen"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Epoch timestamp when DCS was last contacted successfully by Patroni.", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.dcs_last_seen"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.failsafe_mode.active":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.failsafe_mode.active"], "Found a duplicate in the metrics slice: patroni.failsafe_mode.active")
						validatedMetrics["patroni.failsafe_mode.active"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if DCS failsafe mode is currently active, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.failsafe_mode.active"], "Found a duplicate in the metrics slice: patroni.failsafe_mode.active")
						validatedMetrics["patroni.failsafe_mode.active"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if DCS failsafe mode is currently active, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.failsafe_mode.active"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.history.lsn":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.history.lsn"], "Found a duplicate in the metrics slice: patroni.history.lsn")
						validatedMetrics["patroni.history.lsn"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "WAL location (in bytes) at the moment the given timeline was promoted, from the cluster history entry. One data point per historical timeline.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
						patroniHistoryTimelineAttrVal, ok := dp.Attributes().Get("patroni.history.timeline")
						assert.True(t, ok)
						assert.EqualValues(t, 24, patroniHistoryTimelineAttrVal.Int())
						patroniHistoryReasonAttrVal, ok := dp.Attributes().Get("patroni.history.reason")
						assert.True(t, ok)
						assert.Equal(t, "patroni.history.reason-val", patroniHistoryReasonAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.history.lsn"], "Found a duplicate in the metrics slice: patroni.history.lsn")
						validatedMetrics["patroni.history.lsn"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "WAL location (in bytes) at the moment the given timeline was promoted, from the cluster history entry. One data point per historical timeline.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.history.lsn"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.history.timeline")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.history.reason")
						assert.False(t, ok)
					}
				case "patroni.history.promoted_at":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.history.promoted_at"], "Found a duplicate in the metrics slice: patroni.history.promoted_at")
						validatedMetrics["patroni.history.promoted_at"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Epoch timestamp (seconds) when the given timeline was created (promoted), parsed from the cluster history entry. One data point per historical timeline.", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
						patroniHistoryTimelineAttrVal, ok := dp.Attributes().Get("patroni.history.timeline")
						assert.True(t, ok)
						assert.EqualValues(t, 24, patroniHistoryTimelineAttrVal.Int())
						patroniHistoryReasonAttrVal, ok := dp.Attributes().Get("patroni.history.reason")
						assert.True(t, ok)
						assert.Equal(t, "patroni.history.reason-val", patroniHistoryReasonAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.history.promoted_at"], "Found a duplicate in the metrics slice: patroni.history.promoted_at")
						validatedMetrics["patroni.history.promoted_at"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Epoch timestamp (seconds) when the given timeline was created (promoted), parsed from the cluster history entry. One data point per historical timeline.", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["patroni.history.promoted_at"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.history.timeline")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.history.reason")
						assert.False(t, ok)
					}
				case "patroni.history.size":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.history.size"], "Found a duplicate in the metrics slice: patroni.history.size")
						validatedMetrics["patroni.history.size"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Total number of timeline switch (promotion) entries recorded in the cluster history.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.history.size"], "Found a duplicate in the metrics slice: patroni.history.size")
						validatedMetrics["patroni.history.size"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Total number of timeline switch (promotion) entries recorded in the cluster history.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.history.size"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.is_paused":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.is_paused"], "Found a duplicate in the metrics slice: patroni.is_paused")
						validatedMetrics["patroni.is_paused"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if auto failover is disabled (maintenance/pause mode), 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.is_paused"], "Found a duplicate in the metrics slice: patroni.is_paused")
						validatedMetrics["patroni.is_paused"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if auto failover is disabled (maintenance/pause mode), 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.is_paused"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.pending_restart":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.pending_restart"], "Found a duplicate in the metrics slice: patroni.pending_restart")
						validatedMetrics["patroni.pending_restart"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if the node needs a restart, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.pending_restart"], "Found a duplicate in the metrics slice: patroni.pending_restart")
						validatedMetrics["patroni.pending_restart"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if the node needs a restart, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.pending_restart"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.postgres.in_archive_recovery":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.postgres.in_archive_recovery"], "Found a duplicate in the metrics slice: patroni.postgres.in_archive_recovery")
						validatedMetrics["patroni.postgres.in_archive_recovery"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if PostgreSQL is replicating from archive, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.postgres.in_archive_recovery"], "Found a duplicate in the metrics slice: patroni.postgres.in_archive_recovery")
						validatedMetrics["patroni.postgres.in_archive_recovery"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if PostgreSQL is replicating from archive, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.postgres.in_archive_recovery"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.postgres.running":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.postgres.running"], "Found a duplicate in the metrics slice: patroni.postgres.running")
						validatedMetrics["patroni.postgres.running"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if PostgreSQL is running, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
						patroniRoleAttrVal, ok := dp.Attributes().Get("patroni.role")
						assert.True(t, ok)
						assert.Equal(t, "patroni.role-val", patroniRoleAttrVal.Str())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.postgres.running"], "Found a duplicate in the metrics slice: patroni.postgres.running")
						validatedMetrics["patroni.postgres.running"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if PostgreSQL is running, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.postgres.running"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.role")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
					}
				case "patroni.postgres.server_version":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.postgres.server_version"], "Found a duplicate in the metrics slice: patroni.postgres.server_version")
						validatedMetrics["patroni.postgres.server_version"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "PostgreSQL server version (if running), 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.postgres.server_version"], "Found a duplicate in the metrics slice: patroni.postgres.server_version")
						validatedMetrics["patroni.postgres.server_version"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "PostgreSQL server version (if running), 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.postgres.server_version"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.postgres.state":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.postgres.state"], "Found a duplicate in the metrics slice: patroni.postgres.state")
						validatedMetrics["patroni.postgres.state"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Numeric representation of the PostgreSQL state. 0=initdb, 1=initdb_failed, 2=custom_bootstrap, 3=custom_bootstrap_failed, 4=creating_replica, 5=running, 6=starting, 7=bootstrap_starting, 8=start_failed, 9=restarting, 10=restart_failed, 11=stopping, 12=stopped, 13=stop_failed, 14=crashed. Numeric values are fixed and never change for backward compatibility.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
						patroniRoleAttrVal, ok := dp.Attributes().Get("patroni.role")
						assert.True(t, ok)
						assert.Equal(t, "patroni.role-val", patroniRoleAttrVal.Str())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniStateAttrVal, ok := dp.Attributes().Get("patroni.state")
						assert.True(t, ok)
						assert.Equal(t, "patroni.state-val", patroniStateAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.postgres.state"], "Found a duplicate in the metrics slice: patroni.postgres.state")
						validatedMetrics["patroni.postgres.state"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Numeric representation of the PostgreSQL state. 0=initdb, 1=initdb_failed, 2=custom_bootstrap, 3=custom_bootstrap_failed, 4=creating_replica, 5=running, 6=starting, 7=bootstrap_starting, 8=start_failed, 9=restarting, 10=restart_failed, 11=stopping, 12=stopped, 13=stop_failed, 14=crashed. Numeric values are fixed and never change for backward compatibility.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.postgres.state"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.role")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.state")
						assert.False(t, ok)
					}
				case "patroni.postgres.streaming":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.postgres.streaming"], "Found a duplicate in the metrics slice: patroni.postgres.streaming")
						validatedMetrics["patroni.postgres.streaming"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if PostgreSQL is streaming, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.postgres.streaming"], "Found a duplicate in the metrics slice: patroni.postgres.streaming")
						validatedMetrics["patroni.postgres.streaming"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if PostgreSQL is streaming, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.postgres.streaming"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.postgres.timeline":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.postgres.timeline"], "Found a duplicate in the metrics slice: patroni.postgres.timeline")
						validatedMetrics["patroni.postgres.timeline"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "PostgreSQL timeline of this node (if running), 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.postgres.timeline"], "Found a duplicate in the metrics slice: patroni.postgres.timeline")
						validatedMetrics["patroni.postgres.timeline"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "PostgreSQL timeline of this node (if running), 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.postgres.timeline"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.postmaster_start_time":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.postmaster_start_time"], "Found a duplicate in the metrics slice: patroni.postmaster_start_time")
						validatedMetrics["patroni.postmaster_start_time"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Epoch seconds since the PostgreSQL postmaster started.", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.postmaster_start_time"], "Found a duplicate in the metrics slice: patroni.postmaster_start_time")
						validatedMetrics["patroni.postmaster_start_time"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Epoch seconds since the PostgreSQL postmaster started.", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["patroni.postmaster_start_time"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.primary":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.primary"], "Found a duplicate in the metrics slice: patroni.primary")
						validatedMetrics["patroni.primary"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if this node is the leader (primary), 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.primary"], "Found a duplicate in the metrics slice: patroni.primary")
						validatedMetrics["patroni.primary"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if this node is the leader (primary), 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.primary"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.quorum_standby":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.quorum_standby"], "Found a duplicate in the metrics slice: patroni.quorum_standby")
						validatedMetrics["patroni.quorum_standby"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if this node is a quorum standby replica, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.quorum_standby"], "Found a duplicate in the metrics slice: patroni.quorum_standby")
						validatedMetrics["patroni.quorum_standby"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if this node is a quorum standby replica, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.quorum_standby"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.replica":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.replica"], "Found a duplicate in the metrics slice: patroni.replica")
						validatedMetrics["patroni.replica"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if this node is a replica, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.replica"], "Found a duplicate in the metrics slice: patroni.replica")
						validatedMetrics["patroni.replica"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if this node is a replica, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.replica"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.replication.lag":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.replication.lag"], "Found a duplicate in the metrics slice: patroni.replication.lag")
						validatedMetrics["patroni.replication.lag"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Total replication lag in bytes between the standby and the leader.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
						patroniReplicationApplicationNameAttrVal, ok := dp.Attributes().Get("patroni.replication.application_name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.replication.application_name-val", patroniReplicationApplicationNameAttrVal.Str())
						patroniReplicationClientAddrAttrVal, ok := dp.Attributes().Get("patroni.replication.client_addr")
						assert.True(t, ok)
						assert.Equal(t, "patroni.replication.client_addr-val", patroniReplicationClientAddrAttrVal.Str())
						patroniReplicationSyncStateAttrVal, ok := dp.Attributes().Get("patroni.replication.sync_state")
						assert.True(t, ok)
						assert.Equal(t, "patroni.replication.sync_state-val", patroniReplicationSyncStateAttrVal.Str())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.replication.lag"], "Found a duplicate in the metrics slice: patroni.replication.lag")
						validatedMetrics["patroni.replication.lag"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Total replication lag in bytes between the standby and the leader.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.replication.lag"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.replication.application_name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.replication.client_addr")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.replication.sync_state")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
					}
				case "patroni.replication.receive_lag":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.replication.receive_lag"], "Found a duplicate in the metrics slice: patroni.replication.receive_lag")
						validatedMetrics["patroni.replication.receive_lag"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Receive lag in bytes between the leader and the standby.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
						patroniReplicationApplicationNameAttrVal, ok := dp.Attributes().Get("patroni.replication.application_name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.replication.application_name-val", patroniReplicationApplicationNameAttrVal.Str())
						patroniReplicationClientAddrAttrVal, ok := dp.Attributes().Get("patroni.replication.client_addr")
						assert.True(t, ok)
						assert.Equal(t, "patroni.replication.client_addr-val", patroniReplicationClientAddrAttrVal.Str())
						patroniReplicationSyncStateAttrVal, ok := dp.Attributes().Get("patroni.replication.sync_state")
						assert.True(t, ok)
						assert.Equal(t, "patroni.replication.sync_state-val", patroniReplicationSyncStateAttrVal.Str())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.replication.receive_lag"], "Found a duplicate in the metrics slice: patroni.replication.receive_lag")
						validatedMetrics["patroni.replication.receive_lag"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Receive lag in bytes between the leader and the standby.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.replication.receive_lag"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.replication.application_name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.replication.client_addr")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.replication.sync_state")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
					}
				case "patroni.replication.replay_lag":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.replication.replay_lag"], "Found a duplicate in the metrics slice: patroni.replication.replay_lag")
						validatedMetrics["patroni.replication.replay_lag"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Replay lag in bytes between received and replayed WAL on the standby.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
						patroniReplicationApplicationNameAttrVal, ok := dp.Attributes().Get("patroni.replication.application_name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.replication.application_name-val", patroniReplicationApplicationNameAttrVal.Str())
						patroniReplicationClientAddrAttrVal, ok := dp.Attributes().Get("patroni.replication.client_addr")
						assert.True(t, ok)
						assert.Equal(t, "patroni.replication.client_addr-val", patroniReplicationClientAddrAttrVal.Str())
						patroniReplicationSyncStateAttrVal, ok := dp.Attributes().Get("patroni.replication.sync_state")
						assert.True(t, ok)
						assert.Equal(t, "patroni.replication.sync_state-val", patroniReplicationSyncStateAttrVal.Str())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.replication.replay_lag"], "Found a duplicate in the metrics slice: patroni.replication.replay_lag")
						validatedMetrics["patroni.replication.replay_lag"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Replay lag in bytes between received and replayed WAL on the standby.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.replication.replay_lag"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.replication.application_name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.replication.client_addr")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.replication.sync_state")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
					}
				case "patroni.standby_leader":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.standby_leader"], "Found a duplicate in the metrics slice: patroni.standby_leader")
						validatedMetrics["patroni.standby_leader"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if this node is the standby_leader, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.standby_leader"], "Found a duplicate in the metrics slice: patroni.standby_leader")
						validatedMetrics["patroni.standby_leader"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if this node is the standby_leader, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.standby_leader"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.sync_standby":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.sync_standby"], "Found a duplicate in the metrics slice: patroni.sync_standby")
						validatedMetrics["patroni.sync_standby"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if this node is a synchronous standby replica, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.sync_standby"], "Found a duplicate in the metrics slice: patroni.sync_standby")
						validatedMetrics["patroni.sync_standby"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if this node is a synchronous standby replica, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.sync_standby"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.version":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.version"], "Found a duplicate in the metrics slice: patroni.version")
						validatedMetrics["patroni.version"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Patroni semver rendered without periods (e.g. `040000` for `4.0.0`).", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniVersionAttrVal, ok := dp.Attributes().Get("patroni.version")
						assert.True(t, ok)
						assert.Equal(t, "patroni.version-val", patroniVersionAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.version"], "Found a duplicate in the metrics slice: patroni.version")
						validatedMetrics["patroni.version"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Patroni semver rendered without periods (e.g. `040000` for `4.0.0`).", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.version"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.version")
						assert.False(t, ok)
					}
				case "patroni.xlog.location":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.xlog.location"], "Found a duplicate in the metrics slice: patroni.xlog.location")
						validatedMetrics["patroni.xlog.location"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Current location of the PostgreSQL transaction log (WAL), 0 if this node is not the leader.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.xlog.location"], "Found a duplicate in the metrics slice: patroni.xlog.location")
						validatedMetrics["patroni.xlog.location"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Current location of the PostgreSQL transaction log (WAL), 0 if this node is not the leader.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.xlog.location"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.xlog.paused":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.xlog.paused"], "Found a duplicate in the metrics slice: patroni.xlog.paused")
						validatedMetrics["patroni.xlog.paused"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if the PostgreSQL xlog is paused, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.xlog.paused"], "Found a duplicate in the metrics slice: patroni.xlog.paused")
						validatedMetrics["patroni.xlog.paused"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Value is 1 if the PostgreSQL xlog is paused, 0 otherwise.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.xlog.paused"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.xlog.received_location":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.xlog.received_location"], "Found a duplicate in the metrics slice: patroni.xlog.received_location")
						validatedMetrics["patroni.xlog.received_location"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Current location of the received PostgreSQL transaction log, 0 if this node is not a replica.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.xlog.received_location"], "Found a duplicate in the metrics slice: patroni.xlog.received_location")
						validatedMetrics["patroni.xlog.received_location"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Current location of the received PostgreSQL transaction log, 0 if this node is not a replica.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.xlog.received_location"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.xlog.replayed_location":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.xlog.replayed_location"], "Found a duplicate in the metrics slice: patroni.xlog.replayed_location")
						validatedMetrics["patroni.xlog.replayed_location"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Current location of the replayed PostgreSQL transaction log, 0 if this node is not a replica.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.xlog.replayed_location"], "Found a duplicate in the metrics slice: patroni.xlog.replayed_location")
						validatedMetrics["patroni.xlog.replayed_location"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Current location of the replayed PostgreSQL transaction log, 0 if this node is not a replica.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["patroni.xlog.replayed_location"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				case "patroni.xlog.replayed_timestamp":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["patroni.xlog.replayed_timestamp"], "Found a duplicate in the metrics slice: patroni.xlog.replayed_timestamp")
						validatedMetrics["patroni.xlog.replayed_timestamp"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Epoch timestamp of the replayed PostgreSQL transaction log, 0 if null.", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						patroniScopeAttrVal, ok := dp.Attributes().Get("patroni.scope")
						assert.True(t, ok)
						assert.Equal(t, "patroni.scope-val", patroniScopeAttrVal.Str())
						patroniNodeNameAttrVal, ok := dp.Attributes().Get("patroni.node.name")
						assert.True(t, ok)
						assert.Equal(t, "patroni.node.name-val", patroniNodeNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["patroni.xlog.replayed_timestamp"], "Found a duplicate in the metrics slice: patroni.xlog.replayed_timestamp")
						validatedMetrics["patroni.xlog.replayed_timestamp"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Epoch timestamp of the replayed PostgreSQL transaction log, 0 if null.", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["patroni.xlog.replayed_timestamp"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("patroni.scope")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("patroni.node.name")
						assert.False(t, ok)
					}
				}
			}
		})
	}
}
