// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"

	"go.opentelemetry.io/collector/confmap"
)

// PatroniClusterUnlockedMetricAttributeKey specifies the key of an attribute for the patroni.cluster.unlocked metric.
type PatroniClusterUnlockedMetricAttributeKey string

const (
	PatroniClusterUnlockedMetricAttributeKeyPatroniScope    PatroniClusterUnlockedMetricAttributeKey = "patroni.scope"
	PatroniClusterUnlockedMetricAttributeKeyPatroniNodeName PatroniClusterUnlockedMetricAttributeKey = "patroni.node.name"
)

// PatroniClusterUnlockedMetricConfig provides config for the patroni.cluster.unlocked metric.
type PatroniClusterUnlockedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                     `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniClusterUnlockedMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniClusterUnlockedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniClusterUnlockedMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniClusterUnlockedMetricAttributeKeyPatroniScope, PatroniClusterUnlockedMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.cluster.unlocked doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniDcsLastSeenMetricAttributeKey specifies the key of an attribute for the patroni.dcs_last_seen metric.
type PatroniDcsLastSeenMetricAttributeKey string

const (
	PatroniDcsLastSeenMetricAttributeKeyPatroniScope    PatroniDcsLastSeenMetricAttributeKey = "patroni.scope"
	PatroniDcsLastSeenMetricAttributeKeyPatroniNodeName PatroniDcsLastSeenMetricAttributeKey = "patroni.node.name"
)

// PatroniDcsLastSeenMetricConfig provides config for the patroni.dcs_last_seen metric.
type PatroniDcsLastSeenMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniDcsLastSeenMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniDcsLastSeenMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniDcsLastSeenMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniDcsLastSeenMetricAttributeKeyPatroniScope, PatroniDcsLastSeenMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.dcs_last_seen doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniFailsafeModeActiveMetricAttributeKey specifies the key of an attribute for the patroni.failsafe_mode.active metric.
type PatroniFailsafeModeActiveMetricAttributeKey string

const (
	PatroniFailsafeModeActiveMetricAttributeKeyPatroniScope    PatroniFailsafeModeActiveMetricAttributeKey = "patroni.scope"
	PatroniFailsafeModeActiveMetricAttributeKeyPatroniNodeName PatroniFailsafeModeActiveMetricAttributeKey = "patroni.node.name"
)

// PatroniFailsafeModeActiveMetricConfig provides config for the patroni.failsafe_mode.active metric.
type PatroniFailsafeModeActiveMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                        `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniFailsafeModeActiveMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniFailsafeModeActiveMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniFailsafeModeActiveMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniFailsafeModeActiveMetricAttributeKeyPatroniScope, PatroniFailsafeModeActiveMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.failsafe_mode.active doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniHistoryLsnMetricAttributeKey specifies the key of an attribute for the patroni.history.lsn metric.
type PatroniHistoryLsnMetricAttributeKey string

const (
	PatroniHistoryLsnMetricAttributeKeyPatroniScope           PatroniHistoryLsnMetricAttributeKey = "patroni.scope"
	PatroniHistoryLsnMetricAttributeKeyPatroniNodeName        PatroniHistoryLsnMetricAttributeKey = "patroni.node.name"
	PatroniHistoryLsnMetricAttributeKeyPatroniHistoryTimeline PatroniHistoryLsnMetricAttributeKey = "patroni.history.timeline"
	PatroniHistoryLsnMetricAttributeKeyPatroniHistoryReason   PatroniHistoryLsnMetricAttributeKey = "patroni.history.reason"
)

// PatroniHistoryLsnMetricConfig provides config for the patroni.history.lsn metric.
type PatroniHistoryLsnMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniHistoryLsnMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniHistoryLsnMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniHistoryLsnMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniHistoryLsnMetricAttributeKeyPatroniScope, PatroniHistoryLsnMetricAttributeKeyPatroniNodeName, PatroniHistoryLsnMetricAttributeKeyPatroniHistoryTimeline, PatroniHistoryLsnMetricAttributeKeyPatroniHistoryReason:
		default:
			return fmt.Errorf("metric patroni.history.lsn doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name, patroni.history.timeline, patroni.history.reason]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniHistoryPromotedAtMetricAttributeKey specifies the key of an attribute for the patroni.history.promoted_at metric.
type PatroniHistoryPromotedAtMetricAttributeKey string

const (
	PatroniHistoryPromotedAtMetricAttributeKeyPatroniScope           PatroniHistoryPromotedAtMetricAttributeKey = "patroni.scope"
	PatroniHistoryPromotedAtMetricAttributeKeyPatroniNodeName        PatroniHistoryPromotedAtMetricAttributeKey = "patroni.node.name"
	PatroniHistoryPromotedAtMetricAttributeKeyPatroniHistoryTimeline PatroniHistoryPromotedAtMetricAttributeKey = "patroni.history.timeline"
	PatroniHistoryPromotedAtMetricAttributeKeyPatroniHistoryReason   PatroniHistoryPromotedAtMetricAttributeKey = "patroni.history.reason"
)

// PatroniHistoryPromotedAtMetricConfig provides config for the patroni.history.promoted_at metric.
type PatroniHistoryPromotedAtMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                       `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniHistoryPromotedAtMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniHistoryPromotedAtMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniHistoryPromotedAtMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniHistoryPromotedAtMetricAttributeKeyPatroniScope, PatroniHistoryPromotedAtMetricAttributeKeyPatroniNodeName, PatroniHistoryPromotedAtMetricAttributeKeyPatroniHistoryTimeline, PatroniHistoryPromotedAtMetricAttributeKeyPatroniHistoryReason:
		default:
			return fmt.Errorf("metric patroni.history.promoted_at doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name, patroni.history.timeline, patroni.history.reason]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniHistorySizeMetricAttributeKey specifies the key of an attribute for the patroni.history.size metric.
type PatroniHistorySizeMetricAttributeKey string

const (
	PatroniHistorySizeMetricAttributeKeyPatroniScope    PatroniHistorySizeMetricAttributeKey = "patroni.scope"
	PatroniHistorySizeMetricAttributeKeyPatroniNodeName PatroniHistorySizeMetricAttributeKey = "patroni.node.name"
)

// PatroniHistorySizeMetricConfig provides config for the patroni.history.size metric.
type PatroniHistorySizeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniHistorySizeMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniHistorySizeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniHistorySizeMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniHistorySizeMetricAttributeKeyPatroniScope, PatroniHistorySizeMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.history.size doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniIsPausedMetricAttributeKey specifies the key of an attribute for the patroni.is_paused metric.
type PatroniIsPausedMetricAttributeKey string

const (
	PatroniIsPausedMetricAttributeKeyPatroniScope    PatroniIsPausedMetricAttributeKey = "patroni.scope"
	PatroniIsPausedMetricAttributeKeyPatroniNodeName PatroniIsPausedMetricAttributeKey = "patroni.node.name"
)

// PatroniIsPausedMetricConfig provides config for the patroni.is_paused metric.
type PatroniIsPausedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                              `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniIsPausedMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniIsPausedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniIsPausedMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniIsPausedMetricAttributeKeyPatroniScope, PatroniIsPausedMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.is_paused doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniPendingRestartMetricAttributeKey specifies the key of an attribute for the patroni.pending_restart metric.
type PatroniPendingRestartMetricAttributeKey string

const (
	PatroniPendingRestartMetricAttributeKeyPatroniScope    PatroniPendingRestartMetricAttributeKey = "patroni.scope"
	PatroniPendingRestartMetricAttributeKeyPatroniNodeName PatroniPendingRestartMetricAttributeKey = "patroni.node.name"
)

// PatroniPendingRestartMetricConfig provides config for the patroni.pending_restart metric.
type PatroniPendingRestartMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                    `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniPendingRestartMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniPendingRestartMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniPendingRestartMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniPendingRestartMetricAttributeKeyPatroniScope, PatroniPendingRestartMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.pending_restart doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniPostgresInArchiveRecoveryMetricAttributeKey specifies the key of an attribute for the patroni.postgres.in_archive_recovery metric.
type PatroniPostgresInArchiveRecoveryMetricAttributeKey string

const (
	PatroniPostgresInArchiveRecoveryMetricAttributeKeyPatroniScope    PatroniPostgresInArchiveRecoveryMetricAttributeKey = "patroni.scope"
	PatroniPostgresInArchiveRecoveryMetricAttributeKeyPatroniNodeName PatroniPostgresInArchiveRecoveryMetricAttributeKey = "patroni.node.name"
)

// PatroniPostgresInArchiveRecoveryMetricConfig provides config for the patroni.postgres.in_archive_recovery metric.
type PatroniPostgresInArchiveRecoveryMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                               `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniPostgresInArchiveRecoveryMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniPostgresInArchiveRecoveryMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniPostgresInArchiveRecoveryMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniPostgresInArchiveRecoveryMetricAttributeKeyPatroniScope, PatroniPostgresInArchiveRecoveryMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.postgres.in_archive_recovery doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniPostgresRunningMetricAttributeKey specifies the key of an attribute for the patroni.postgres.running metric.
type PatroniPostgresRunningMetricAttributeKey string

const (
	PatroniPostgresRunningMetricAttributeKeyPatroniNodeName PatroniPostgresRunningMetricAttributeKey = "patroni.node.name"
	PatroniPostgresRunningMetricAttributeKeyPatroniRole     PatroniPostgresRunningMetricAttributeKey = "patroni.role"
	PatroniPostgresRunningMetricAttributeKeyPatroniScope    PatroniPostgresRunningMetricAttributeKey = "patroni.scope"
)

// PatroniPostgresRunningMetricConfig provides config for the patroni.postgres.running metric.
type PatroniPostgresRunningMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                     `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniPostgresRunningMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniPostgresRunningMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniPostgresRunningMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniPostgresRunningMetricAttributeKeyPatroniNodeName, PatroniPostgresRunningMetricAttributeKeyPatroniRole, PatroniPostgresRunningMetricAttributeKeyPatroniScope:
		default:
			return fmt.Errorf("metric patroni.postgres.running doesn't have an attribute %v, valid attributes: [patroni.node.name, patroni.role, patroni.scope]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniPostgresServerVersionMetricAttributeKey specifies the key of an attribute for the patroni.postgres.server_version metric.
type PatroniPostgresServerVersionMetricAttributeKey string

const (
	PatroniPostgresServerVersionMetricAttributeKeyPatroniScope    PatroniPostgresServerVersionMetricAttributeKey = "patroni.scope"
	PatroniPostgresServerVersionMetricAttributeKeyPatroniNodeName PatroniPostgresServerVersionMetricAttributeKey = "patroni.node.name"
)

// PatroniPostgresServerVersionMetricConfig provides config for the patroni.postgres.server_version metric.
type PatroniPostgresServerVersionMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                           `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniPostgresServerVersionMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniPostgresServerVersionMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniPostgresServerVersionMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniPostgresServerVersionMetricAttributeKeyPatroniScope, PatroniPostgresServerVersionMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.postgres.server_version doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniPostgresStateMetricAttributeKey specifies the key of an attribute for the patroni.postgres.state metric.
type PatroniPostgresStateMetricAttributeKey string

const (
	PatroniPostgresStateMetricAttributeKeyPatroniNodeName PatroniPostgresStateMetricAttributeKey = "patroni.node.name"
	PatroniPostgresStateMetricAttributeKeyPatroniRole     PatroniPostgresStateMetricAttributeKey = "patroni.role"
	PatroniPostgresStateMetricAttributeKeyPatroniScope    PatroniPostgresStateMetricAttributeKey = "patroni.scope"
	PatroniPostgresStateMetricAttributeKeyPatroniState    PatroniPostgresStateMetricAttributeKey = "patroni.state"
)

// PatroniPostgresStateMetricConfig provides config for the patroni.postgres.state metric.
type PatroniPostgresStateMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniPostgresStateMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniPostgresStateMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniPostgresStateMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniPostgresStateMetricAttributeKeyPatroniNodeName, PatroniPostgresStateMetricAttributeKeyPatroniRole, PatroniPostgresStateMetricAttributeKeyPatroniScope, PatroniPostgresStateMetricAttributeKeyPatroniState:
		default:
			return fmt.Errorf("metric patroni.postgres.state doesn't have an attribute %v, valid attributes: [patroni.node.name, patroni.role, patroni.scope, patroni.state]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniPostgresStreamingMetricAttributeKey specifies the key of an attribute for the patroni.postgres.streaming metric.
type PatroniPostgresStreamingMetricAttributeKey string

const (
	PatroniPostgresStreamingMetricAttributeKeyPatroniScope    PatroniPostgresStreamingMetricAttributeKey = "patroni.scope"
	PatroniPostgresStreamingMetricAttributeKeyPatroniNodeName PatroniPostgresStreamingMetricAttributeKey = "patroni.node.name"
)

// PatroniPostgresStreamingMetricConfig provides config for the patroni.postgres.streaming metric.
type PatroniPostgresStreamingMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                       `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniPostgresStreamingMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniPostgresStreamingMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniPostgresStreamingMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniPostgresStreamingMetricAttributeKeyPatroniScope, PatroniPostgresStreamingMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.postgres.streaming doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniPostgresTimelineMetricAttributeKey specifies the key of an attribute for the patroni.postgres.timeline metric.
type PatroniPostgresTimelineMetricAttributeKey string

const (
	PatroniPostgresTimelineMetricAttributeKeyPatroniScope    PatroniPostgresTimelineMetricAttributeKey = "patroni.scope"
	PatroniPostgresTimelineMetricAttributeKeyPatroniNodeName PatroniPostgresTimelineMetricAttributeKey = "patroni.node.name"
)

// PatroniPostgresTimelineMetricConfig provides config for the patroni.postgres.timeline metric.
type PatroniPostgresTimelineMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                      `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniPostgresTimelineMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniPostgresTimelineMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniPostgresTimelineMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniPostgresTimelineMetricAttributeKeyPatroniScope, PatroniPostgresTimelineMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.postgres.timeline doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniPostmasterStartTimeMetricAttributeKey specifies the key of an attribute for the patroni.postmaster_start_time metric.
type PatroniPostmasterStartTimeMetricAttributeKey string

const (
	PatroniPostmasterStartTimeMetricAttributeKeyPatroniScope    PatroniPostmasterStartTimeMetricAttributeKey = "patroni.scope"
	PatroniPostmasterStartTimeMetricAttributeKeyPatroniNodeName PatroniPostmasterStartTimeMetricAttributeKey = "patroni.node.name"
)

// PatroniPostmasterStartTimeMetricConfig provides config for the patroni.postmaster_start_time metric.
type PatroniPostmasterStartTimeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                         `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniPostmasterStartTimeMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniPostmasterStartTimeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniPostmasterStartTimeMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniPostmasterStartTimeMetricAttributeKeyPatroniScope, PatroniPostmasterStartTimeMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.postmaster_start_time doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniPrimaryMetricAttributeKey specifies the key of an attribute for the patroni.primary metric.
type PatroniPrimaryMetricAttributeKey string

const (
	PatroniPrimaryMetricAttributeKeyPatroniScope    PatroniPrimaryMetricAttributeKey = "patroni.scope"
	PatroniPrimaryMetricAttributeKeyPatroniNodeName PatroniPrimaryMetricAttributeKey = "patroni.node.name"
)

// PatroniPrimaryMetricConfig provides config for the patroni.primary metric.
type PatroniPrimaryMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                             `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniPrimaryMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniPrimaryMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniPrimaryMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniPrimaryMetricAttributeKeyPatroniScope, PatroniPrimaryMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.primary doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniQuorumStandbyMetricAttributeKey specifies the key of an attribute for the patroni.quorum_standby metric.
type PatroniQuorumStandbyMetricAttributeKey string

const (
	PatroniQuorumStandbyMetricAttributeKeyPatroniScope    PatroniQuorumStandbyMetricAttributeKey = "patroni.scope"
	PatroniQuorumStandbyMetricAttributeKeyPatroniNodeName PatroniQuorumStandbyMetricAttributeKey = "patroni.node.name"
)

// PatroniQuorumStandbyMetricConfig provides config for the patroni.quorum_standby metric.
type PatroniQuorumStandbyMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniQuorumStandbyMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniQuorumStandbyMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniQuorumStandbyMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniQuorumStandbyMetricAttributeKeyPatroniScope, PatroniQuorumStandbyMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.quorum_standby doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniReplicaMetricAttributeKey specifies the key of an attribute for the patroni.replica metric.
type PatroniReplicaMetricAttributeKey string

const (
	PatroniReplicaMetricAttributeKeyPatroniScope    PatroniReplicaMetricAttributeKey = "patroni.scope"
	PatroniReplicaMetricAttributeKeyPatroniNodeName PatroniReplicaMetricAttributeKey = "patroni.node.name"
)

// PatroniReplicaMetricConfig provides config for the patroni.replica metric.
type PatroniReplicaMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                             `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniReplicaMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniReplicaMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniReplicaMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniReplicaMetricAttributeKeyPatroniScope, PatroniReplicaMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.replica doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniReplicationLagMetricAttributeKey specifies the key of an attribute for the patroni.replication.lag metric.
type PatroniReplicationLagMetricAttributeKey string

const (
	PatroniReplicationLagMetricAttributeKeyPatroniNodeName                   PatroniReplicationLagMetricAttributeKey = "patroni.node.name"
	PatroniReplicationLagMetricAttributeKeyPatroniReplicationApplicationName PatroniReplicationLagMetricAttributeKey = "patroni.replication.application_name"
	PatroniReplicationLagMetricAttributeKeyPatroniReplicationClientAddr      PatroniReplicationLagMetricAttributeKey = "patroni.replication.client_addr"
	PatroniReplicationLagMetricAttributeKeyPatroniReplicationSyncState       PatroniReplicationLagMetricAttributeKey = "patroni.replication.sync_state"
	PatroniReplicationLagMetricAttributeKeyPatroniScope                      PatroniReplicationLagMetricAttributeKey = "patroni.scope"
)

// PatroniReplicationLagMetricConfig provides config for the patroni.replication.lag metric.
type PatroniReplicationLagMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                    `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniReplicationLagMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniReplicationLagMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniReplicationLagMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniReplicationLagMetricAttributeKeyPatroniNodeName, PatroniReplicationLagMetricAttributeKeyPatroniReplicationApplicationName, PatroniReplicationLagMetricAttributeKeyPatroniReplicationClientAddr, PatroniReplicationLagMetricAttributeKeyPatroniReplicationSyncState, PatroniReplicationLagMetricAttributeKeyPatroniScope:
		default:
			return fmt.Errorf("metric patroni.replication.lag doesn't have an attribute %v, valid attributes: [patroni.node.name, patroni.replication.application_name, patroni.replication.client_addr, patroni.replication.sync_state, patroni.scope]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniReplicationReceiveLagMetricAttributeKey specifies the key of an attribute for the patroni.replication.receive_lag metric.
type PatroniReplicationReceiveLagMetricAttributeKey string

const (
	PatroniReplicationReceiveLagMetricAttributeKeyPatroniNodeName                   PatroniReplicationReceiveLagMetricAttributeKey = "patroni.node.name"
	PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationApplicationName PatroniReplicationReceiveLagMetricAttributeKey = "patroni.replication.application_name"
	PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationClientAddr      PatroniReplicationReceiveLagMetricAttributeKey = "patroni.replication.client_addr"
	PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationSyncState       PatroniReplicationReceiveLagMetricAttributeKey = "patroni.replication.sync_state"
	PatroniReplicationReceiveLagMetricAttributeKeyPatroniScope                      PatroniReplicationReceiveLagMetricAttributeKey = "patroni.scope"
)

// PatroniReplicationReceiveLagMetricConfig provides config for the patroni.replication.receive_lag metric.
type PatroniReplicationReceiveLagMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                           `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniReplicationReceiveLagMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniReplicationReceiveLagMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniReplicationReceiveLagMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniReplicationReceiveLagMetricAttributeKeyPatroniNodeName, PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationApplicationName, PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationClientAddr, PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationSyncState, PatroniReplicationReceiveLagMetricAttributeKeyPatroniScope:
		default:
			return fmt.Errorf("metric patroni.replication.receive_lag doesn't have an attribute %v, valid attributes: [patroni.node.name, patroni.replication.application_name, patroni.replication.client_addr, patroni.replication.sync_state, patroni.scope]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniReplicationReplayLagMetricAttributeKey specifies the key of an attribute for the patroni.replication.replay_lag metric.
type PatroniReplicationReplayLagMetricAttributeKey string

const (
	PatroniReplicationReplayLagMetricAttributeKeyPatroniNodeName                   PatroniReplicationReplayLagMetricAttributeKey = "patroni.node.name"
	PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationApplicationName PatroniReplicationReplayLagMetricAttributeKey = "patroni.replication.application_name"
	PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationClientAddr      PatroniReplicationReplayLagMetricAttributeKey = "patroni.replication.client_addr"
	PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationSyncState       PatroniReplicationReplayLagMetricAttributeKey = "patroni.replication.sync_state"
	PatroniReplicationReplayLagMetricAttributeKeyPatroniScope                      PatroniReplicationReplayLagMetricAttributeKey = "patroni.scope"
)

// PatroniReplicationReplayLagMetricConfig provides config for the patroni.replication.replay_lag metric.
type PatroniReplicationReplayLagMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniReplicationReplayLagMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniReplicationReplayLagMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniReplicationReplayLagMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniReplicationReplayLagMetricAttributeKeyPatroniNodeName, PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationApplicationName, PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationClientAddr, PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationSyncState, PatroniReplicationReplayLagMetricAttributeKeyPatroniScope:
		default:
			return fmt.Errorf("metric patroni.replication.replay_lag doesn't have an attribute %v, valid attributes: [patroni.node.name, patroni.replication.application_name, patroni.replication.client_addr, patroni.replication.sync_state, patroni.scope]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniStandbyLeaderMetricAttributeKey specifies the key of an attribute for the patroni.standby_leader metric.
type PatroniStandbyLeaderMetricAttributeKey string

const (
	PatroniStandbyLeaderMetricAttributeKeyPatroniScope    PatroniStandbyLeaderMetricAttributeKey = "patroni.scope"
	PatroniStandbyLeaderMetricAttributeKeyPatroniNodeName PatroniStandbyLeaderMetricAttributeKey = "patroni.node.name"
)

// PatroniStandbyLeaderMetricConfig provides config for the patroni.standby_leader metric.
type PatroniStandbyLeaderMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniStandbyLeaderMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniStandbyLeaderMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniStandbyLeaderMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniStandbyLeaderMetricAttributeKeyPatroniScope, PatroniStandbyLeaderMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.standby_leader doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniSyncStandbyMetricAttributeKey specifies the key of an attribute for the patroni.sync_standby metric.
type PatroniSyncStandbyMetricAttributeKey string

const (
	PatroniSyncStandbyMetricAttributeKeyPatroniScope    PatroniSyncStandbyMetricAttributeKey = "patroni.scope"
	PatroniSyncStandbyMetricAttributeKeyPatroniNodeName PatroniSyncStandbyMetricAttributeKey = "patroni.node.name"
)

// PatroniSyncStandbyMetricConfig provides config for the patroni.sync_standby metric.
type PatroniSyncStandbyMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniSyncStandbyMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniSyncStandbyMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniSyncStandbyMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniSyncStandbyMetricAttributeKeyPatroniScope, PatroniSyncStandbyMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.sync_standby doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniVersionMetricAttributeKey specifies the key of an attribute for the patroni.version metric.
type PatroniVersionMetricAttributeKey string

const (
	PatroniVersionMetricAttributeKeyPatroniNodeName PatroniVersionMetricAttributeKey = "patroni.node.name"
	PatroniVersionMetricAttributeKeyPatroniScope    PatroniVersionMetricAttributeKey = "patroni.scope"
	PatroniVersionMetricAttributeKeyPatroniVersion  PatroniVersionMetricAttributeKey = "patroni.version"
)

// PatroniVersionMetricConfig provides config for the patroni.version metric.
type PatroniVersionMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                             `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniVersionMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniVersionMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniVersionMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniVersionMetricAttributeKeyPatroniNodeName, PatroniVersionMetricAttributeKeyPatroniScope, PatroniVersionMetricAttributeKeyPatroniVersion:
		default:
			return fmt.Errorf("metric patroni.version doesn't have an attribute %v, valid attributes: [patroni.node.name, patroni.scope, patroni.version]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniXlogLocationMetricAttributeKey specifies the key of an attribute for the patroni.xlog.location metric.
type PatroniXlogLocationMetricAttributeKey string

const (
	PatroniXlogLocationMetricAttributeKeyPatroniScope    PatroniXlogLocationMetricAttributeKey = "patroni.scope"
	PatroniXlogLocationMetricAttributeKeyPatroniNodeName PatroniXlogLocationMetricAttributeKey = "patroni.node.name"
)

// PatroniXlogLocationMetricConfig provides config for the patroni.xlog.location metric.
type PatroniXlogLocationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                  `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniXlogLocationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniXlogLocationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniXlogLocationMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniXlogLocationMetricAttributeKeyPatroniScope, PatroniXlogLocationMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.xlog.location doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniXlogPausedMetricAttributeKey specifies the key of an attribute for the patroni.xlog.paused metric.
type PatroniXlogPausedMetricAttributeKey string

const (
	PatroniXlogPausedMetricAttributeKeyPatroniScope    PatroniXlogPausedMetricAttributeKey = "patroni.scope"
	PatroniXlogPausedMetricAttributeKeyPatroniNodeName PatroniXlogPausedMetricAttributeKey = "patroni.node.name"
)

// PatroniXlogPausedMetricConfig provides config for the patroni.xlog.paused metric.
type PatroniXlogPausedMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniXlogPausedMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniXlogPausedMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniXlogPausedMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniXlogPausedMetricAttributeKeyPatroniScope, PatroniXlogPausedMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.xlog.paused doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniXlogReceivedLocationMetricAttributeKey specifies the key of an attribute for the patroni.xlog.received_location metric.
type PatroniXlogReceivedLocationMetricAttributeKey string

const (
	PatroniXlogReceivedLocationMetricAttributeKeyPatroniScope    PatroniXlogReceivedLocationMetricAttributeKey = "patroni.scope"
	PatroniXlogReceivedLocationMetricAttributeKeyPatroniNodeName PatroniXlogReceivedLocationMetricAttributeKey = "patroni.node.name"
)

// PatroniXlogReceivedLocationMetricConfig provides config for the patroni.xlog.received_location metric.
type PatroniXlogReceivedLocationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniXlogReceivedLocationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniXlogReceivedLocationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniXlogReceivedLocationMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniXlogReceivedLocationMetricAttributeKeyPatroniScope, PatroniXlogReceivedLocationMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.xlog.received_location doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniXlogReplayedLocationMetricAttributeKey specifies the key of an attribute for the patroni.xlog.replayed_location metric.
type PatroniXlogReplayedLocationMetricAttributeKey string

const (
	PatroniXlogReplayedLocationMetricAttributeKeyPatroniScope    PatroniXlogReplayedLocationMetricAttributeKey = "patroni.scope"
	PatroniXlogReplayedLocationMetricAttributeKeyPatroniNodeName PatroniXlogReplayedLocationMetricAttributeKey = "patroni.node.name"
)

// PatroniXlogReplayedLocationMetricConfig provides config for the patroni.xlog.replayed_location metric.
type PatroniXlogReplayedLocationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniXlogReplayedLocationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniXlogReplayedLocationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniXlogReplayedLocationMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniXlogReplayedLocationMetricAttributeKeyPatroniScope, PatroniXlogReplayedLocationMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.xlog.replayed_location doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// PatroniXlogReplayedTimestampMetricAttributeKey specifies the key of an attribute for the patroni.xlog.replayed_timestamp metric.
type PatroniXlogReplayedTimestampMetricAttributeKey string

const (
	PatroniXlogReplayedTimestampMetricAttributeKeyPatroniScope    PatroniXlogReplayedTimestampMetricAttributeKey = "patroni.scope"
	PatroniXlogReplayedTimestampMetricAttributeKeyPatroniNodeName PatroniXlogReplayedTimestampMetricAttributeKey = "patroni.node.name"
)

// PatroniXlogReplayedTimestampMetricConfig provides config for the patroni.xlog.replayed_timestamp metric.
type PatroniXlogReplayedTimestampMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                           `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []PatroniXlogReplayedTimestampMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *PatroniXlogReplayedTimestampMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *PatroniXlogReplayedTimestampMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case PatroniXlogReplayedTimestampMetricAttributeKeyPatroniScope, PatroniXlogReplayedTimestampMetricAttributeKeyPatroniNodeName:
		default:
			return fmt.Errorf("metric patroni.xlog.replayed_timestamp doesn't have an attribute %v, valid attributes: [patroni.scope, patroni.node.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// MetricsConfig provides config for patronireceiver metrics.
type MetricsConfig struct {
	PatroniClusterUnlocked           PatroniClusterUnlockedMetricConfig           `mapstructure:"patroni.cluster.unlocked"`
	PatroniDcsLastSeen               PatroniDcsLastSeenMetricConfig               `mapstructure:"patroni.dcs_last_seen"`
	PatroniFailsafeModeActive        PatroniFailsafeModeActiveMetricConfig        `mapstructure:"patroni.failsafe_mode.active"`
	PatroniHistoryLsn                PatroniHistoryLsnMetricConfig                `mapstructure:"patroni.history.lsn"`
	PatroniHistoryPromotedAt         PatroniHistoryPromotedAtMetricConfig         `mapstructure:"patroni.history.promoted_at"`
	PatroniHistorySize               PatroniHistorySizeMetricConfig               `mapstructure:"patroni.history.size"`
	PatroniIsPaused                  PatroniIsPausedMetricConfig                  `mapstructure:"patroni.is_paused"`
	PatroniPendingRestart            PatroniPendingRestartMetricConfig            `mapstructure:"patroni.pending_restart"`
	PatroniPostgresInArchiveRecovery PatroniPostgresInArchiveRecoveryMetricConfig `mapstructure:"patroni.postgres.in_archive_recovery"`
	PatroniPostgresRunning           PatroniPostgresRunningMetricConfig           `mapstructure:"patroni.postgres.running"`
	PatroniPostgresServerVersion     PatroniPostgresServerVersionMetricConfig     `mapstructure:"patroni.postgres.server_version"`
	PatroniPostgresState             PatroniPostgresStateMetricConfig             `mapstructure:"patroni.postgres.state"`
	PatroniPostgresStreaming         PatroniPostgresStreamingMetricConfig         `mapstructure:"patroni.postgres.streaming"`
	PatroniPostgresTimeline          PatroniPostgresTimelineMetricConfig          `mapstructure:"patroni.postgres.timeline"`
	PatroniPostmasterStartTime       PatroniPostmasterStartTimeMetricConfig       `mapstructure:"patroni.postmaster_start_time"`
	PatroniPrimary                   PatroniPrimaryMetricConfig                   `mapstructure:"patroni.primary"`
	PatroniQuorumStandby             PatroniQuorumStandbyMetricConfig             `mapstructure:"patroni.quorum_standby"`
	PatroniReplica                   PatroniReplicaMetricConfig                   `mapstructure:"patroni.replica"`
	PatroniReplicationLag            PatroniReplicationLagMetricConfig            `mapstructure:"patroni.replication.lag"`
	PatroniReplicationReceiveLag     PatroniReplicationReceiveLagMetricConfig     `mapstructure:"patroni.replication.receive_lag"`
	PatroniReplicationReplayLag      PatroniReplicationReplayLagMetricConfig      `mapstructure:"patroni.replication.replay_lag"`
	PatroniStandbyLeader             PatroniStandbyLeaderMetricConfig             `mapstructure:"patroni.standby_leader"`
	PatroniSyncStandby               PatroniSyncStandbyMetricConfig               `mapstructure:"patroni.sync_standby"`
	PatroniVersion                   PatroniVersionMetricConfig                   `mapstructure:"patroni.version"`
	PatroniXlogLocation              PatroniXlogLocationMetricConfig              `mapstructure:"patroni.xlog.location"`
	PatroniXlogPaused                PatroniXlogPausedMetricConfig                `mapstructure:"patroni.xlog.paused"`
	PatroniXlogReceivedLocation      PatroniXlogReceivedLocationMetricConfig      `mapstructure:"patroni.xlog.received_location"`
	PatroniXlogReplayedLocation      PatroniXlogReplayedLocationMetricConfig      `mapstructure:"patroni.xlog.replayed_location"`
	PatroniXlogReplayedTimestamp     PatroniXlogReplayedTimestampMetricConfig     `mapstructure:"patroni.xlog.replayed_timestamp"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		PatroniClusterUnlocked: PatroniClusterUnlockedMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniClusterUnlockedMetricAttributeKey{PatroniClusterUnlockedMetricAttributeKeyPatroniScope, PatroniClusterUnlockedMetricAttributeKeyPatroniNodeName},
		},
		PatroniDcsLastSeen: PatroniDcsLastSeenMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniDcsLastSeenMetricAttributeKey{PatroniDcsLastSeenMetricAttributeKeyPatroniScope, PatroniDcsLastSeenMetricAttributeKeyPatroniNodeName},
		},
		PatroniFailsafeModeActive: PatroniFailsafeModeActiveMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniFailsafeModeActiveMetricAttributeKey{PatroniFailsafeModeActiveMetricAttributeKeyPatroniScope, PatroniFailsafeModeActiveMetricAttributeKeyPatroniNodeName},
		},
		PatroniHistoryLsn: PatroniHistoryLsnMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniHistoryLsnMetricAttributeKey{PatroniHistoryLsnMetricAttributeKeyPatroniScope, PatroniHistoryLsnMetricAttributeKeyPatroniNodeName, PatroniHistoryLsnMetricAttributeKeyPatroniHistoryTimeline, PatroniHistoryLsnMetricAttributeKeyPatroniHistoryReason},
		},
		PatroniHistoryPromotedAt: PatroniHistoryPromotedAtMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniHistoryPromotedAtMetricAttributeKey{PatroniHistoryPromotedAtMetricAttributeKeyPatroniScope, PatroniHistoryPromotedAtMetricAttributeKeyPatroniNodeName, PatroniHistoryPromotedAtMetricAttributeKeyPatroniHistoryTimeline, PatroniHistoryPromotedAtMetricAttributeKeyPatroniHistoryReason},
		},
		PatroniHistorySize: PatroniHistorySizeMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniHistorySizeMetricAttributeKey{PatroniHistorySizeMetricAttributeKeyPatroniScope, PatroniHistorySizeMetricAttributeKeyPatroniNodeName},
		},
		PatroniIsPaused: PatroniIsPausedMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniIsPausedMetricAttributeKey{PatroniIsPausedMetricAttributeKeyPatroniScope, PatroniIsPausedMetricAttributeKeyPatroniNodeName},
		},
		PatroniPendingRestart: PatroniPendingRestartMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniPendingRestartMetricAttributeKey{PatroniPendingRestartMetricAttributeKeyPatroniScope, PatroniPendingRestartMetricAttributeKeyPatroniNodeName},
		},
		PatroniPostgresInArchiveRecovery: PatroniPostgresInArchiveRecoveryMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniPostgresInArchiveRecoveryMetricAttributeKey{PatroniPostgresInArchiveRecoveryMetricAttributeKeyPatroniScope, PatroniPostgresInArchiveRecoveryMetricAttributeKeyPatroniNodeName},
		},
		PatroniPostgresRunning: PatroniPostgresRunningMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniPostgresRunningMetricAttributeKey{PatroniPostgresRunningMetricAttributeKeyPatroniNodeName, PatroniPostgresRunningMetricAttributeKeyPatroniRole, PatroniPostgresRunningMetricAttributeKeyPatroniScope},
		},
		PatroniPostgresServerVersion: PatroniPostgresServerVersionMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniPostgresServerVersionMetricAttributeKey{PatroniPostgresServerVersionMetricAttributeKeyPatroniScope, PatroniPostgresServerVersionMetricAttributeKeyPatroniNodeName},
		},
		PatroniPostgresState: PatroniPostgresStateMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniPostgresStateMetricAttributeKey{PatroniPostgresStateMetricAttributeKeyPatroniNodeName, PatroniPostgresStateMetricAttributeKeyPatroniRole, PatroniPostgresStateMetricAttributeKeyPatroniScope, PatroniPostgresStateMetricAttributeKeyPatroniState},
		},
		PatroniPostgresStreaming: PatroniPostgresStreamingMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniPostgresStreamingMetricAttributeKey{PatroniPostgresStreamingMetricAttributeKeyPatroniScope, PatroniPostgresStreamingMetricAttributeKeyPatroniNodeName},
		},
		PatroniPostgresTimeline: PatroniPostgresTimelineMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []PatroniPostgresTimelineMetricAttributeKey{PatroniPostgresTimelineMetricAttributeKeyPatroniScope, PatroniPostgresTimelineMetricAttributeKeyPatroniNodeName},
		},
		PatroniPostmasterStartTime: PatroniPostmasterStartTimeMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniPostmasterStartTimeMetricAttributeKey{PatroniPostmasterStartTimeMetricAttributeKeyPatroniScope, PatroniPostmasterStartTimeMetricAttributeKeyPatroniNodeName},
		},
		PatroniPrimary: PatroniPrimaryMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniPrimaryMetricAttributeKey{PatroniPrimaryMetricAttributeKeyPatroniScope, PatroniPrimaryMetricAttributeKeyPatroniNodeName},
		},
		PatroniQuorumStandby: PatroniQuorumStandbyMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniQuorumStandbyMetricAttributeKey{PatroniQuorumStandbyMetricAttributeKeyPatroniScope, PatroniQuorumStandbyMetricAttributeKeyPatroniNodeName},
		},
		PatroniReplica: PatroniReplicaMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniReplicaMetricAttributeKey{PatroniReplicaMetricAttributeKeyPatroniScope, PatroniReplicaMetricAttributeKeyPatroniNodeName},
		},
		PatroniReplicationLag: PatroniReplicationLagMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniReplicationLagMetricAttributeKey{PatroniReplicationLagMetricAttributeKeyPatroniNodeName, PatroniReplicationLagMetricAttributeKeyPatroniReplicationApplicationName, PatroniReplicationLagMetricAttributeKeyPatroniReplicationClientAddr, PatroniReplicationLagMetricAttributeKeyPatroniReplicationSyncState, PatroniReplicationLagMetricAttributeKeyPatroniScope},
		},
		PatroniReplicationReceiveLag: PatroniReplicationReceiveLagMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniReplicationReceiveLagMetricAttributeKey{PatroniReplicationReceiveLagMetricAttributeKeyPatroniNodeName, PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationApplicationName, PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationClientAddr, PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationSyncState, PatroniReplicationReceiveLagMetricAttributeKeyPatroniScope},
		},
		PatroniReplicationReplayLag: PatroniReplicationReplayLagMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniReplicationReplayLagMetricAttributeKey{PatroniReplicationReplayLagMetricAttributeKeyPatroniNodeName, PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationApplicationName, PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationClientAddr, PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationSyncState, PatroniReplicationReplayLagMetricAttributeKeyPatroniScope},
		},
		PatroniStandbyLeader: PatroniStandbyLeaderMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniStandbyLeaderMetricAttributeKey{PatroniStandbyLeaderMetricAttributeKeyPatroniScope, PatroniStandbyLeaderMetricAttributeKeyPatroniNodeName},
		},
		PatroniSyncStandby: PatroniSyncStandbyMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniSyncStandbyMetricAttributeKey{PatroniSyncStandbyMetricAttributeKeyPatroniScope, PatroniSyncStandbyMetricAttributeKeyPatroniNodeName},
		},
		PatroniVersion: PatroniVersionMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniVersionMetricAttributeKey{PatroniVersionMetricAttributeKeyPatroniNodeName, PatroniVersionMetricAttributeKeyPatroniScope, PatroniVersionMetricAttributeKeyPatroniVersion},
		},
		PatroniXlogLocation: PatroniXlogLocationMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []PatroniXlogLocationMetricAttributeKey{PatroniXlogLocationMetricAttributeKeyPatroniScope, PatroniXlogLocationMetricAttributeKeyPatroniNodeName},
		},
		PatroniXlogPaused: PatroniXlogPausedMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniXlogPausedMetricAttributeKey{PatroniXlogPausedMetricAttributeKeyPatroniScope, PatroniXlogPausedMetricAttributeKeyPatroniNodeName},
		},
		PatroniXlogReceivedLocation: PatroniXlogReceivedLocationMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []PatroniXlogReceivedLocationMetricAttributeKey{PatroniXlogReceivedLocationMetricAttributeKeyPatroniScope, PatroniXlogReceivedLocationMetricAttributeKeyPatroniNodeName},
		},
		PatroniXlogReplayedLocation: PatroniXlogReplayedLocationMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []PatroniXlogReplayedLocationMetricAttributeKey{PatroniXlogReplayedLocationMetricAttributeKeyPatroniScope, PatroniXlogReplayedLocationMetricAttributeKeyPatroniNodeName},
		},
		PatroniXlogReplayedTimestamp: PatroniXlogReplayedTimestampMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []PatroniXlogReplayedTimestampMetricAttributeKey{PatroniXlogReplayedTimestampMetricAttributeKeyPatroniScope, PatroniXlogReplayedTimestampMetricAttributeKeyPatroniNodeName},
		},
	}
}

// MetricsBuilderConfig is a configuration for patronireceiver metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
