// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					PatroniClusterUnlocked: PatroniClusterUnlockedMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniClusterUnlockedMetricAttributeKey{PatroniClusterUnlockedMetricAttributeKeyPatroniScope, PatroniClusterUnlockedMetricAttributeKeyPatroniNodeName},
					},
					PatroniDcsLastSeen: PatroniDcsLastSeenMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniDcsLastSeenMetricAttributeKey{PatroniDcsLastSeenMetricAttributeKeyPatroniScope, PatroniDcsLastSeenMetricAttributeKeyPatroniNodeName},
					},
					PatroniFailsafeModeActive: PatroniFailsafeModeActiveMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniFailsafeModeActiveMetricAttributeKey{PatroniFailsafeModeActiveMetricAttributeKeyPatroniScope, PatroniFailsafeModeActiveMetricAttributeKeyPatroniNodeName},
					},
					PatroniHistoryLsn: PatroniHistoryLsnMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniHistoryLsnMetricAttributeKey{PatroniHistoryLsnMetricAttributeKeyPatroniScope, PatroniHistoryLsnMetricAttributeKeyPatroniNodeName, PatroniHistoryLsnMetricAttributeKeyPatroniHistoryTimeline, PatroniHistoryLsnMetricAttributeKeyPatroniHistoryReason},
					},
					PatroniHistoryPromotedAt: PatroniHistoryPromotedAtMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniHistoryPromotedAtMetricAttributeKey{PatroniHistoryPromotedAtMetricAttributeKeyPatroniScope, PatroniHistoryPromotedAtMetricAttributeKeyPatroniNodeName, PatroniHistoryPromotedAtMetricAttributeKeyPatroniHistoryTimeline, PatroniHistoryPromotedAtMetricAttributeKeyPatroniHistoryReason},
					},
					PatroniHistorySize: PatroniHistorySizeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniHistorySizeMetricAttributeKey{PatroniHistorySizeMetricAttributeKeyPatroniScope, PatroniHistorySizeMetricAttributeKeyPatroniNodeName},
					},
					PatroniIsPaused: PatroniIsPausedMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniIsPausedMetricAttributeKey{PatroniIsPausedMetricAttributeKeyPatroniScope, PatroniIsPausedMetricAttributeKeyPatroniNodeName},
					},
					PatroniPendingRestart: PatroniPendingRestartMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPendingRestartMetricAttributeKey{PatroniPendingRestartMetricAttributeKeyPatroniScope, PatroniPendingRestartMetricAttributeKeyPatroniNodeName},
					},
					PatroniPostgresInArchiveRecovery: PatroniPostgresInArchiveRecoveryMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPostgresInArchiveRecoveryMetricAttributeKey{PatroniPostgresInArchiveRecoveryMetricAttributeKeyPatroniScope, PatroniPostgresInArchiveRecoveryMetricAttributeKeyPatroniNodeName},
					},
					PatroniPostgresRunning: PatroniPostgresRunningMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPostgresRunningMetricAttributeKey{PatroniPostgresRunningMetricAttributeKeyPatroniNodeName, PatroniPostgresRunningMetricAttributeKeyPatroniRole, PatroniPostgresRunningMetricAttributeKeyPatroniScope},
					},
					PatroniPostgresServerVersion: PatroniPostgresServerVersionMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPostgresServerVersionMetricAttributeKey{PatroniPostgresServerVersionMetricAttributeKeyPatroniScope, PatroniPostgresServerVersionMetricAttributeKeyPatroniNodeName},
					},
					PatroniPostgresState: PatroniPostgresStateMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPostgresStateMetricAttributeKey{PatroniPostgresStateMetricAttributeKeyPatroniNodeName, PatroniPostgresStateMetricAttributeKeyPatroniRole, PatroniPostgresStateMetricAttributeKeyPatroniScope, PatroniPostgresStateMetricAttributeKeyPatroniState},
					},
					PatroniPostgresStreaming: PatroniPostgresStreamingMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPostgresStreamingMetricAttributeKey{PatroniPostgresStreamingMetricAttributeKeyPatroniScope, PatroniPostgresStreamingMetricAttributeKeyPatroniNodeName},
					},
					PatroniPostgresTimeline: PatroniPostgresTimelineMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []PatroniPostgresTimelineMetricAttributeKey{PatroniPostgresTimelineMetricAttributeKeyPatroniScope, PatroniPostgresTimelineMetricAttributeKeyPatroniNodeName},
					},
					PatroniPostmasterStartTime: PatroniPostmasterStartTimeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPostmasterStartTimeMetricAttributeKey{PatroniPostmasterStartTimeMetricAttributeKeyPatroniScope, PatroniPostmasterStartTimeMetricAttributeKeyPatroniNodeName},
					},
					PatroniPrimary: PatroniPrimaryMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPrimaryMetricAttributeKey{PatroniPrimaryMetricAttributeKeyPatroniScope, PatroniPrimaryMetricAttributeKeyPatroniNodeName},
					},
					PatroniQuorumStandby: PatroniQuorumStandbyMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniQuorumStandbyMetricAttributeKey{PatroniQuorumStandbyMetricAttributeKeyPatroniScope, PatroniQuorumStandbyMetricAttributeKeyPatroniNodeName},
					},
					PatroniReplica: PatroniReplicaMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniReplicaMetricAttributeKey{PatroniReplicaMetricAttributeKeyPatroniScope, PatroniReplicaMetricAttributeKeyPatroniNodeName},
					},
					PatroniReplicationLag: PatroniReplicationLagMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniReplicationLagMetricAttributeKey{PatroniReplicationLagMetricAttributeKeyPatroniNodeName, PatroniReplicationLagMetricAttributeKeyPatroniReplicationApplicationName, PatroniReplicationLagMetricAttributeKeyPatroniReplicationClientAddr, PatroniReplicationLagMetricAttributeKeyPatroniReplicationSyncState, PatroniReplicationLagMetricAttributeKeyPatroniScope},
					},
					PatroniReplicationReceiveLag: PatroniReplicationReceiveLagMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniReplicationReceiveLagMetricAttributeKey{PatroniReplicationReceiveLagMetricAttributeKeyPatroniNodeName, PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationApplicationName, PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationClientAddr, PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationSyncState, PatroniReplicationReceiveLagMetricAttributeKeyPatroniScope},
					},
					PatroniReplicationReplayLag: PatroniReplicationReplayLagMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniReplicationReplayLagMetricAttributeKey{PatroniReplicationReplayLagMetricAttributeKeyPatroniNodeName, PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationApplicationName, PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationClientAddr, PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationSyncState, PatroniReplicationReplayLagMetricAttributeKeyPatroniScope},
					},
					PatroniStandbyLeader: PatroniStandbyLeaderMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniStandbyLeaderMetricAttributeKey{PatroniStandbyLeaderMetricAttributeKeyPatroniScope, PatroniStandbyLeaderMetricAttributeKeyPatroniNodeName},
					},
					PatroniSyncStandby: PatroniSyncStandbyMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniSyncStandbyMetricAttributeKey{PatroniSyncStandbyMetricAttributeKeyPatroniScope, PatroniSyncStandbyMetricAttributeKeyPatroniNodeName},
					},
					PatroniVersion: PatroniVersionMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniVersionMetricAttributeKey{PatroniVersionMetricAttributeKeyPatroniNodeName, PatroniVersionMetricAttributeKeyPatroniScope, PatroniVersionMetricAttributeKeyPatroniVersion},
					},
					PatroniXlogLocation: PatroniXlogLocationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []PatroniXlogLocationMetricAttributeKey{PatroniXlogLocationMetricAttributeKeyPatroniScope, PatroniXlogLocationMetricAttributeKeyPatroniNodeName},
					},
					PatroniXlogPaused: PatroniXlogPausedMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniXlogPausedMetricAttributeKey{PatroniXlogPausedMetricAttributeKeyPatroniScope, PatroniXlogPausedMetricAttributeKeyPatroniNodeName},
					},
					PatroniXlogReceivedLocation: PatroniXlogReceivedLocationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []PatroniXlogReceivedLocationMetricAttributeKey{PatroniXlogReceivedLocationMetricAttributeKeyPatroniScope, PatroniXlogReceivedLocationMetricAttributeKeyPatroniNodeName},
					},
					PatroniXlogReplayedLocation: PatroniXlogReplayedLocationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []PatroniXlogReplayedLocationMetricAttributeKey{PatroniXlogReplayedLocationMetricAttributeKeyPatroniScope, PatroniXlogReplayedLocationMetricAttributeKeyPatroniNodeName},
					},
					PatroniXlogReplayedTimestamp: PatroniXlogReplayedTimestampMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniXlogReplayedTimestampMetricAttributeKey{PatroniXlogReplayedTimestampMetricAttributeKeyPatroniScope, PatroniXlogReplayedTimestampMetricAttributeKeyPatroniNodeName},
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					PatroniClusterUnlocked: PatroniClusterUnlockedMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniClusterUnlockedMetricAttributeKey{PatroniClusterUnlockedMetricAttributeKeyPatroniScope, PatroniClusterUnlockedMetricAttributeKeyPatroniNodeName},
					},
					PatroniDcsLastSeen: PatroniDcsLastSeenMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniDcsLastSeenMetricAttributeKey{PatroniDcsLastSeenMetricAttributeKeyPatroniScope, PatroniDcsLastSeenMetricAttributeKeyPatroniNodeName},
					},
					PatroniFailsafeModeActive: PatroniFailsafeModeActiveMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniFailsafeModeActiveMetricAttributeKey{PatroniFailsafeModeActiveMetricAttributeKeyPatroniScope, PatroniFailsafeModeActiveMetricAttributeKeyPatroniNodeName},
					},
					PatroniHistoryLsn: PatroniHistoryLsnMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniHistoryLsnMetricAttributeKey{PatroniHistoryLsnMetricAttributeKeyPatroniScope, PatroniHistoryLsnMetricAttributeKeyPatroniNodeName, PatroniHistoryLsnMetricAttributeKeyPatroniHistoryTimeline, PatroniHistoryLsnMetricAttributeKeyPatroniHistoryReason},
					},
					PatroniHistoryPromotedAt: PatroniHistoryPromotedAtMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniHistoryPromotedAtMetricAttributeKey{PatroniHistoryPromotedAtMetricAttributeKeyPatroniScope, PatroniHistoryPromotedAtMetricAttributeKeyPatroniNodeName, PatroniHistoryPromotedAtMetricAttributeKeyPatroniHistoryTimeline, PatroniHistoryPromotedAtMetricAttributeKeyPatroniHistoryReason},
					},
					PatroniHistorySize: PatroniHistorySizeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniHistorySizeMetricAttributeKey{PatroniHistorySizeMetricAttributeKeyPatroniScope, PatroniHistorySizeMetricAttributeKeyPatroniNodeName},
					},
					PatroniIsPaused: PatroniIsPausedMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniIsPausedMetricAttributeKey{PatroniIsPausedMetricAttributeKeyPatroniScope, PatroniIsPausedMetricAttributeKeyPatroniNodeName},
					},
					PatroniPendingRestart: PatroniPendingRestartMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPendingRestartMetricAttributeKey{PatroniPendingRestartMetricAttributeKeyPatroniScope, PatroniPendingRestartMetricAttributeKeyPatroniNodeName},
					},
					PatroniPostgresInArchiveRecovery: PatroniPostgresInArchiveRecoveryMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPostgresInArchiveRecoveryMetricAttributeKey{PatroniPostgresInArchiveRecoveryMetricAttributeKeyPatroniScope, PatroniPostgresInArchiveRecoveryMetricAttributeKeyPatroniNodeName},
					},
					PatroniPostgresRunning: PatroniPostgresRunningMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPostgresRunningMetricAttributeKey{PatroniPostgresRunningMetricAttributeKeyPatroniNodeName, PatroniPostgresRunningMetricAttributeKeyPatroniRole, PatroniPostgresRunningMetricAttributeKeyPatroniScope},
					},
					PatroniPostgresServerVersion: PatroniPostgresServerVersionMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPostgresServerVersionMetricAttributeKey{PatroniPostgresServerVersionMetricAttributeKeyPatroniScope, PatroniPostgresServerVersionMetricAttributeKeyPatroniNodeName},
					},
					PatroniPostgresState: PatroniPostgresStateMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPostgresStateMetricAttributeKey{PatroniPostgresStateMetricAttributeKeyPatroniNodeName, PatroniPostgresStateMetricAttributeKeyPatroniRole, PatroniPostgresStateMetricAttributeKeyPatroniScope, PatroniPostgresStateMetricAttributeKeyPatroniState},
					},
					PatroniPostgresStreaming: PatroniPostgresStreamingMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPostgresStreamingMetricAttributeKey{PatroniPostgresStreamingMetricAttributeKeyPatroniScope, PatroniPostgresStreamingMetricAttributeKeyPatroniNodeName},
					},
					PatroniPostgresTimeline: PatroniPostgresTimelineMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []PatroniPostgresTimelineMetricAttributeKey{PatroniPostgresTimelineMetricAttributeKeyPatroniScope, PatroniPostgresTimelineMetricAttributeKeyPatroniNodeName},
					},
					PatroniPostmasterStartTime: PatroniPostmasterStartTimeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPostmasterStartTimeMetricAttributeKey{PatroniPostmasterStartTimeMetricAttributeKeyPatroniScope, PatroniPostmasterStartTimeMetricAttributeKeyPatroniNodeName},
					},
					PatroniPrimary: PatroniPrimaryMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniPrimaryMetricAttributeKey{PatroniPrimaryMetricAttributeKeyPatroniScope, PatroniPrimaryMetricAttributeKeyPatroniNodeName},
					},
					PatroniQuorumStandby: PatroniQuorumStandbyMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniQuorumStandbyMetricAttributeKey{PatroniQuorumStandbyMetricAttributeKeyPatroniScope, PatroniQuorumStandbyMetricAttributeKeyPatroniNodeName},
					},
					PatroniReplica: PatroniReplicaMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniReplicaMetricAttributeKey{PatroniReplicaMetricAttributeKeyPatroniScope, PatroniReplicaMetricAttributeKeyPatroniNodeName},
					},
					PatroniReplicationLag: PatroniReplicationLagMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniReplicationLagMetricAttributeKey{PatroniReplicationLagMetricAttributeKeyPatroniNodeName, PatroniReplicationLagMetricAttributeKeyPatroniReplicationApplicationName, PatroniReplicationLagMetricAttributeKeyPatroniReplicationClientAddr, PatroniReplicationLagMetricAttributeKeyPatroniReplicationSyncState, PatroniReplicationLagMetricAttributeKeyPatroniScope},
					},
					PatroniReplicationReceiveLag: PatroniReplicationReceiveLagMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniReplicationReceiveLagMetricAttributeKey{PatroniReplicationReceiveLagMetricAttributeKeyPatroniNodeName, PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationApplicationName, PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationClientAddr, PatroniReplicationReceiveLagMetricAttributeKeyPatroniReplicationSyncState, PatroniReplicationReceiveLagMetricAttributeKeyPatroniScope},
					},
					PatroniReplicationReplayLag: PatroniReplicationReplayLagMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniReplicationReplayLagMetricAttributeKey{PatroniReplicationReplayLagMetricAttributeKeyPatroniNodeName, PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationApplicationName, PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationClientAddr, PatroniReplicationReplayLagMetricAttributeKeyPatroniReplicationSyncState, PatroniReplicationReplayLagMetricAttributeKeyPatroniScope},
					},
					PatroniStandbyLeader: PatroniStandbyLeaderMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniStandbyLeaderMetricAttributeKey{PatroniStandbyLeaderMetricAttributeKeyPatroniScope, PatroniStandbyLeaderMetricAttributeKeyPatroniNodeName},
					},
					PatroniSyncStandby: PatroniSyncStandbyMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniSyncStandbyMetricAttributeKey{PatroniSyncStandbyMetricAttributeKeyPatroniScope, PatroniSyncStandbyMetricAttributeKeyPatroniNodeName},
					},
					PatroniVersion: PatroniVersionMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniVersionMetricAttributeKey{PatroniVersionMetricAttributeKeyPatroniNodeName, PatroniVersionMetricAttributeKeyPatroniScope, PatroniVersionMetricAttributeKeyPatroniVersion},
					},
					PatroniXlogLocation: PatroniXlogLocationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []PatroniXlogLocationMetricAttributeKey{PatroniXlogLocationMetricAttributeKeyPatroniScope, PatroniXlogLocationMetricAttributeKeyPatroniNodeName},
					},
					PatroniXlogPaused: PatroniXlogPausedMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniXlogPausedMetricAttributeKey{PatroniXlogPausedMetricAttributeKeyPatroniScope, PatroniXlogPausedMetricAttributeKeyPatroniNodeName},
					},
					PatroniXlogReceivedLocation: PatroniXlogReceivedLocationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []PatroniXlogReceivedLocationMetricAttributeKey{PatroniXlogReceivedLocationMetricAttributeKeyPatroniScope, PatroniXlogReceivedLocationMetricAttributeKeyPatroniNodeName},
					},
					PatroniXlogReplayedLocation: PatroniXlogReplayedLocationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []PatroniXlogReplayedLocationMetricAttributeKey{PatroniXlogReplayedLocationMetricAttributeKeyPatroniScope, PatroniXlogReplayedLocationMetricAttributeKeyPatroniNodeName},
					},
					PatroniXlogReplayedTimestamp: PatroniXlogReplayedTimestampMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []PatroniXlogReplayedTimestampMetricAttributeKey{PatroniXlogReplayedTimestampMetricAttributeKeyPatroniScope, PatroniXlogReplayedTimestampMetricAttributeKeyPatroniNodeName},
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(PatroniClusterUnlockedMetricConfig{}, PatroniDcsLastSeenMetricConfig{}, PatroniFailsafeModeActiveMetricConfig{}, PatroniHistoryLsnMetricConfig{}, PatroniHistoryPromotedAtMetricConfig{}, PatroniHistorySizeMetricConfig{}, PatroniIsPausedMetricConfig{}, PatroniPendingRestartMetricConfig{}, PatroniPostgresInArchiveRecoveryMetricConfig{}, PatroniPostgresRunningMetricConfig{}, PatroniPostgresServerVersionMetricConfig{}, PatroniPostgresStateMetricConfig{}, PatroniPostgresStreamingMetricConfig{}, PatroniPostgresTimelineMetricConfig{}, PatroniPostmasterStartTimeMetricConfig{}, PatroniPrimaryMetricConfig{}, PatroniQuorumStandbyMetricConfig{}, PatroniReplicaMetricConfig{}, PatroniReplicationLagMetricConfig{}, PatroniReplicationReceiveLagMetricConfig{}, PatroniReplicationReplayLagMetricConfig{}, PatroniStandbyLeaderMetricConfig{}, PatroniSyncStandbyMetricConfig{}, PatroniVersionMetricConfig{}, PatroniXlogLocationMetricConfig{}, PatroniXlogPausedMetricConfig{}, PatroniXlogReceivedLocationMetricConfig{}, PatroniXlogReplayedLocationMetricConfig{}, PatroniXlogReplayedTimestampMetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestPatroniClusterUnlockedMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniClusterUnlocked
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniClusterUnlockedMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.cluster.unlocked doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniClusterUnlocked
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniDcsLastSeenMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniDcsLastSeen
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniDcsLastSeenMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.dcs_last_seen doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniDcsLastSeen
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniFailsafeModeActiveMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniFailsafeModeActive
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniFailsafeModeActiveMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.failsafe_mode.active doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniFailsafeModeActive
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniHistoryLsnMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniHistoryLsn
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniHistoryLsnMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.history.lsn doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name, patroni.history.timeline, patroni.history.reason]")

	cfg = DefaultMetricsConfig().PatroniHistoryLsn
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniHistoryPromotedAtMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniHistoryPromotedAt
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniHistoryPromotedAtMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.history.promoted_at doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name, patroni.history.timeline, patroni.history.reason]")

	cfg = DefaultMetricsConfig().PatroniHistoryPromotedAt
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniHistorySizeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniHistorySize
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniHistorySizeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.history.size doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniHistorySize
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniIsPausedMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniIsPaused
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniIsPausedMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.is_paused doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniIsPaused
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniPendingRestartMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniPendingRestart
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniPendingRestartMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.pending_restart doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniPendingRestart
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniPostgresInArchiveRecoveryMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniPostgresInArchiveRecovery
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniPostgresInArchiveRecoveryMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.postgres.in_archive_recovery doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniPostgresInArchiveRecovery
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniPostgresRunningMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniPostgresRunning
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniPostgresRunningMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.postgres.running doesn't have an attribute invalid, valid attributes: [patroni.node.name, patroni.role, patroni.scope]")

	cfg = DefaultMetricsConfig().PatroniPostgresRunning
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniPostgresServerVersionMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniPostgresServerVersion
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniPostgresServerVersionMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.postgres.server_version doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniPostgresServerVersion
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniPostgresStateMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniPostgresState
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniPostgresStateMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.postgres.state doesn't have an attribute invalid, valid attributes: [patroni.node.name, patroni.role, patroni.scope, patroni.state]")

	cfg = DefaultMetricsConfig().PatroniPostgresState
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniPostgresStreamingMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniPostgresStreaming
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniPostgresStreamingMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.postgres.streaming doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniPostgresStreaming
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniPostgresTimelineMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniPostgresTimeline
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniPostgresTimelineMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.postgres.timeline doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniPostgresTimeline
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniPostmasterStartTimeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniPostmasterStartTime
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniPostmasterStartTimeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.postmaster_start_time doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniPostmasterStartTime
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniPrimaryMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniPrimary
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniPrimaryMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.primary doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniPrimary
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniQuorumStandbyMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniQuorumStandby
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniQuorumStandbyMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.quorum_standby doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniQuorumStandby
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniReplicaMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniReplica
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniReplicaMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.replica doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniReplica
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniReplicationLagMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniReplicationLag
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniReplicationLagMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.replication.lag doesn't have an attribute invalid, valid attributes: [patroni.node.name, patroni.replication.application_name, patroni.replication.client_addr, patroni.replication.sync_state, patroni.scope]")

	cfg = DefaultMetricsConfig().PatroniReplicationLag
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniReplicationReceiveLagMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniReplicationReceiveLag
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniReplicationReceiveLagMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.replication.receive_lag doesn't have an attribute invalid, valid attributes: [patroni.node.name, patroni.replication.application_name, patroni.replication.client_addr, patroni.replication.sync_state, patroni.scope]")

	cfg = DefaultMetricsConfig().PatroniReplicationReceiveLag
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniReplicationReplayLagMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniReplicationReplayLag
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniReplicationReplayLagMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.replication.replay_lag doesn't have an attribute invalid, valid attributes: [patroni.node.name, patroni.replication.application_name, patroni.replication.client_addr, patroni.replication.sync_state, patroni.scope]")

	cfg = DefaultMetricsConfig().PatroniReplicationReplayLag
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniStandbyLeaderMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniStandbyLeader
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniStandbyLeaderMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.standby_leader doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniStandbyLeader
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniSyncStandbyMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniSyncStandby
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniSyncStandbyMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.sync_standby doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniSyncStandby
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniVersionMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniVersion
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniVersionMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.version doesn't have an attribute invalid, valid attributes: [patroni.node.name, patroni.scope, patroni.version]")

	cfg = DefaultMetricsConfig().PatroniVersion
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniXlogLocationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniXlogLocation
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniXlogLocationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.xlog.location doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniXlogLocation
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniXlogPausedMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniXlogPaused
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniXlogPausedMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.xlog.paused doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniXlogPaused
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniXlogReceivedLocationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniXlogReceivedLocation
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniXlogReceivedLocationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.xlog.received_location doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniXlogReceivedLocation
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniXlogReplayedLocationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniXlogReplayedLocation
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniXlogReplayedLocationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.xlog.replayed_location doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniXlogReplayedLocation
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestPatroniXlogReplayedTimestampMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().PatroniXlogReplayedTimestamp
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []PatroniXlogReplayedTimestampMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric patroni.xlog.replayed_timestamp doesn't have an attribute invalid, valid attributes: [patroni.scope, patroni.node.name]")

	cfg = DefaultMetricsConfig().PatroniXlogReplayedTimestamp
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
